name: Validate LaTeX Document
on: [ push, pull_request ]
jobs:
  test_building_book:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
      - name: Test baking the release versions
        uses: docker://ghcr.io/hendricius:the-sourdough-framework:latest
        with:
          run: |
            cd book
            make -j build_pdf build_serif_ebook
